# Generated by Django 3.1.3 on 2023-08-16 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('desc', models.CharField(max_length=500, verbose_name='用例描述')),
                ('creator_id', models.IntegerField(default=0, verbose_name='创建人id')),
                ('project_id', models.IntegerField(verbose_name='项目id')),
                ('filename', models.CharField(default='', max_length=200, verbose_name='文件名')),
                ('filepath', models.CharField(default='', max_length=500, verbose_name='文件路径')),
            ],
            options={
                'db_table': 'case',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='项目名称')),
                ('git_repository', models.CharField(blank=True, max_length=100, null=True, verbose_name='Git仓库')),
                ('git_branch', models.CharField(blank=True, max_length=100, null=True, verbose_name='Git分支')),
                ('last_sync_time', models.DateTimeField(blank=True, null=True, verbose_name='上次同步时间')),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='测试计划名称')),
                ('project_id', models.IntegerField(verbose_name='项目id')),
                ('task_status', models.CharField(blank=True, default='0', max_length=1, null=True, verbose_name='定时任务开关状态')),
                ('task_crontab', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='定时任务crontab表达式')),
            ],
            options={
                'db_table': 'task',
            },
        ),
        migrations.CreateModel(
            name='TaskCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField(verbose_name='任务id')),
                ('case_id', models.IntegerField(verbose_name='用例id')),
            ],
            options={
                'db_table': 'task_case',
            },
        ),
        migrations.CreateModel(
            name='TaskResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField(verbose_name='任务id')),
                ('result', models.CharField(max_length=50, verbose_name='运行结果')),
                ('run_time', models.DateTimeField(auto_now=True, verbose_name='运行时间')),
                ('run_user_id', models.IntegerField(default=0, verbose_name='运行人id')),
                ('report_path', models.CharField(default='', max_length=300, verbose_name='测试报告')),
            ],
            options={
                'db_table': 'task_result',
            },
        ),
    ]
